// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkOVnIglXpkzWgfbTPtQ4eJGtI60ECAY8',
    appId: '1:684546770806:web:6abbdda72d161c80ac5c57',
    messagingSenderId: '684546770806',
    projectId: 'duser-85041',
    authDomain: 'duser-85041.firebaseapp.com',
    databaseURL: 'https://duser-85041-default-rtdb.firebaseio.com',
    storageBucket: 'duser-85041.appspot.com',
    measurementId: 'G-908K4CCJGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA10ln0Z0k7NEhEFE1kE4EbCEuuSVKyEHA',
    appId: '1:684546770806:android:dc8fea5f19799f4aac5c57',
    messagingSenderId: '684546770806',
    projectId: 'duser-85041',
    databaseURL: 'https://duser-85041-default-rtdb.firebaseio.com',
    storageBucket: 'duser-85041.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMvo4fcb3Vcr1sJ_4EjgmhAtdmWiTHIvw',
    appId: '1:684546770806:ios:f1a9bd0dcc802b85ac5c57',
    messagingSenderId: '684546770806',
    projectId: 'duser-85041',
    databaseURL: 'https://duser-85041-default-rtdb.firebaseio.com',
    storageBucket: 'duser-85041.appspot.com',
    iosClientId: '684546770806-070pmfrnhjj6fgdb24konkr1mq27mrea.apps.googleusercontent.com',
    iosBundleId: 'com.example.duser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMvo4fcb3Vcr1sJ_4EjgmhAtdmWiTHIvw',
    appId: '1:684546770806:ios:f1a9bd0dcc802b85ac5c57',
    messagingSenderId: '684546770806',
    projectId: 'duser-85041',
    databaseURL: 'https://duser-85041-default-rtdb.firebaseio.com',
    storageBucket: 'duser-85041.appspot.com',
    iosClientId: '684546770806-070pmfrnhjj6fgdb24konkr1mq27mrea.apps.googleusercontent.com',
    iosBundleId: 'com.example.duser',
  );
}
